ALTER TABLE users DROP CONSTRAINT IF EXISTS users_pkey;

ALTER TABLE users DROP COLUMN IF EXISTS id;

ALTER TABLE users DROP CONSTRAINT IF EXISTS users_email_unique;

ALTER TABLE users ADD PRIMARY KEY (email);
