ALTER TABLE users DROP CONSTRAINT IF EXISTS users_pkey;

ALTER TABLE users ALTER COLUMN email TYPE TEXT;
ALTER TABLE users ALTER COLUMN email SET NOT NULL;

ALTER TABLE users ADD CONSTRAINT users_email_unique UNIQUE (email);

ALTER TABLE users ADD COLUMN id SERIAL;

ALTER TABLE users ADD PRIMARY KEY (id);
